import type { Metadata } from "next";
import "./globals.css";
import MainLayout from "@/app/component/main-layout";
import { ChatProvider } from "@/context/chat";
import { Providers } from "@/app/component/providers";
import { auth } from "@/auth";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  console.log('Session in HeaderDetails:', session);
  return (
    <html lang="en">
      <body>
        {
          session?.user ? (
            <Providers session={session}>
              <ChatProvider>
                <MainLayout>
                  {children}
                </MainLayout>
              </ChatProvider>
            </Providers>
          ) : children
        }
      </body>
    </html >
  );
}
