import type { Metadata } from "next";
import "./globals.css";
import MainLayout from "@/app/component/main-layout";
import { ChatProvider } from "@/context/chat";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ChatProvider>
          <MainLayout>
            {children}
          </MainLayout>
        </ChatProvider>
      </body>
    </html >
  );
}
