import type { Metadata } from "next";
import "./globals.css";
import MainLayout from "@/app/component/main-layout";
import { ChatProvider } from "@/context/chat";
import { Providers } from "@/app/component/providers";
import { auth } from "@/auth";
import { findChatHistroy } from "@/actions/sql";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  const chatHistroyRes = await findChatHistroy({ userId: session?.user?.id || 'unknown_user' });
  const chatHistroy = chatHistroyRes.success && chatHistroyRes.data ? chatHistroyRes.data : [];
  console.log('Session in HeaderDetails:', session, session?.user?.id || 'unknown_user', chatHistroyRes, chatHistroy);
  return (
    <html lang="en">
      <body>
        {
          session?.user ? (
            <Providers session={session}>
              <ChatProvider>
                <MainLayout chatHistroy={chatHistroy}>
                  {children}
                </MainLayout>
              </ChatProvider>
            </Providers>
          ) : children
        }
      </body>
    </html >
  );
}
